const appConfig = {
  cloud: true,
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/intro/index',
    'pages/home/index',
    'pages/tasks/index',
    'pages/categories/index',
    'pages/search/index',
    'pages/publish/index',
    'pages/messages/index',
    'pages/profile/index',
    'pages/nearby-map/index',
    'pages/provider/index',
    'pages/task-detail/index',
    'pages/payment/index',
    'pages/refund/index',
    'pages/chat/index',
    'pages/apply-detail/index',
    'pages/my-tasks/index',
    'pages/order-detail/index',
    'pages/orders/index',
    'pages/kyc/index',
    'pages/worker-center/index',
    'pages/wallet/index',
    'pages/agreement/index',
    'pages/report/index',
    'pages/ai-assistant/index',
    'pages/product-detail/index',
    'pages/webview/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '有应帮',
    navigationBarTextStyle: 'black',
  },
  permission: {
    'scope.userLocation': {
      desc: '用于推荐附近同城任务，并帮助你选择服务地址',
    },
  },
  requiredPrivateInfos: ['getLocation', 'chooseLocation'],
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#FF6A00',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: './assets/tabbar/house.png',
        selectedIconPath: './assets/tabbar/house-active.png',
      },
      {
        pagePath: 'pages/tasks/index',
        text: '需求广场',
        iconPath: './assets/tabbar/tasks.png',
        selectedIconPath: './assets/tabbar/tasks-active.png',
      },
      {
        pagePath: 'pages/publish/index',
        text: '发布',
        iconPath: './assets/tabbar/plus-circle.png',
        selectedIconPath: './assets/tabbar/plus-circle-active.png',
      },
      {
        pagePath: 'pages/orders/index',
        text: '订单',
        iconPath: './assets/tabbar/messages.png',
        selectedIconPath: './assets/tabbar/messages-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
};

export default defineAppConfig(appConfig as any);
